### ISSUE TITLE
Pass in config as param?

### ISSUE THREAD

**Issue by ryanblock** [ryanblock/august-connect#15]
Not sure if anyone is interested, but perhaps folks would prefer credential configs to be passed in as a param instead of loaded via env vars?

Any thoughts?

**Comment by cbartram** [comment]
Env works well because the params are generally secrets. So we would load them as env's into our own app only to transition them to a map to pass into the August Connect Module.

**Comment by ryanblock** [comment]
Yeah, that's generally my thoughts, although it's good to know when I'm being overly prescriptive.

How's the module going for you otherwise? What are you using it for? What can be improved?

**Comment by blaineam** [comment]
I just used this module to update a home bridge plugin for august smart locks so that I can used Homekit with the non Homekit capable smart locks. working great so far. for my use case being able to pass them in would be better than manually assigning values to process.env however it is working great overall.

**Comment by cbartram** [comment]
Im actually pairing this module with my Nest camera! I use a deep learning model to identify facial similarities through a screenshot of my nest camera and then if the face is recognized I use `august-connect` to automatically unlock the front door.

Working really well for me so far!

**Comment by ryanblock** [comment]
🙌🏻🙌🏻🙌🏻

**Comment by ryanblock** [comment]
Just shipped `3.0.0` RC which includes support for config as params. Additionally, I've removed support for Node.js 8 (now EOL, although made no incompatible changes, so it should work fine for quite a while to come).

Note: I have not yet tested this on real hardware, so it may contain boogs! Would appreciate testing and feedback.

- Install: `npm i august-connect@RC`
- Docs: https://github.com/ryanblock/august-connect/tree/auth-params#config-object
- Changelog: https://github.com/ryanblock/august-connect/blob/auth-params/changelog.md#300

**Comment by cbartram** [comment]
Thanks I'll update!

**Comment by ryanblock** [comment]
Sweet!

**Comment by wootwoot1234** [comment]
@ryanblock I've been playing around with the RC branch, I'm very happy with it so far, good work!  My use case is with multiple august accounts so I can't use the env variables.  It seems more flexible to me to only use the param option and allow people to retrieve their credentials from env variables on their own (maybe even include an example of how to do it in the readme).  I know it would be a major breaking change but I think it would be worth it as opposed to trying to maintain code that uses both options and it's confusing to people getting started with the library.  

Right now, if you use the following code it's not working and I think it's because of the `locks: locks.bind({}, {internal: false})` code in the index.js file.

    const result = await August.locks({config});
    console.log("result", result);

I'm excited to start using this code.

**Comment by ryanblock** [comment]
@wootwoot1234 right on! This (3.0.0) is already a breaking change so that's fine, but what's the reasoning behind retiring env vars instead of a config object?

Good call on that bind call, will fix that asap.

**Comment by ryanblock** [comment]
Bind call fixed in RC-3 (out now), tested fine here but would be glad to get more eyes on it.

**Comment by ryanblock** [comment]
3.0.0 now out!
